### ISSUE TITLE
cpanratings.perl.org no longer exists

### ISSUE THREAD

**Issue by pjacklam** [shlomif/perl-Module-Format#1]
This distribution has a link to CPAN Ratings at cpanratings.perl.org, but this address now redirects to https://metacpan.org/

**Comment by shlomif** [comment]
On Wed, 12 Apr 2023 23:44:51 -0700
Peter John Acklam ***@***.***> wrote:

> This distribution has a link to CPAN Ratings at cpanratings.perl.org, but
> this address now redirects to https://metacpan.org/
> 

hi Peter,

please stop this script.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://is.gd/i5eMQd - Emma Watson’s Interview for a Software Dev Job

Chuck Norris wrote solutions for all the problems of
https://en.wikipedia.org/wiki/Project_Euler , and they all run in under a
minute. In total.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by pjacklam** [comment]
> hi Peter, please stop this script.

There is no script. Anyway, I won't post any more issues regarding your distributions.
