### ISSUE TITLE
Modification of a read-only value attempted at lib/Text/Format.pm line 57

### ISSUE THREAD

**Issue by mikecappella** [shlomif/perl-Module-Format#2]
This code below produces the error in the subject.  I've tripped over this several times.

```
use Text::Format;

my $F = Text::Format->new;

print $F->format($_)	for ('one two three', 'four');
```

It can be avoided if $_ is declared as _local_ - precede line 57 of Text/Format.pm with:

```
local $_;
```

**Comment by shlomif** [comment]
@mikecappella : thanks for reporting this issue! I think the issue should be fixed in the CPAN v0.63 release.

Note that I usually opted to replacing `$_` with `my $nextword`.

**Comment by shlomif** [comment]
@mikecappella : oh, and please test the new release

**Comment by mikecappella** [comment]
Works fine, thanks for the quick turnaround.

**Comment by shlomif** [comment]
@mikecappella : thanks!
